#!/bin/bash
#
#
#########################################################
# Name: pyfirewall (main script)
# Porpose: Main script pyfirewall runner
# Writer: Gianluca Pernigoto <jeanlucperni@gmail.com>
# Copyright: (c) 2013-2015 Gianluca Pernigoto <jeanlucperni@gmail.com>
# license: GPL3
# Version: (V0.12) Tuesday, 14 August 2012
# Rev (v0.13) 06/02/2015
#
# LONG DESCRIPTION:
#
# This script is a convenient and reliable way for running the firewall 
# daemon localized in /etc/rc.d/rc.firewall or /etc/init.d/firewall,
# this depend what init-systems is used (System V or BSD style ?).
# Also, it is check for a regular starting of pyfirewall program .
##########################################################

path2=/etc/pyfirewall

# you must be root
if [ $(id -u) -ne 0 ]; then
        echo -e "\033[31;1mPermission denied !\033[0m you must be root"
        exit 1
fi

# whereis firewall daemon? 
if [ -e /etc/rc.d/rc.firewall ]; then
	path1=/etc/rc.d/rc.firewall
	
elif [ -e /etc/init.d/firewall ]; then
	path1=/etc/init.d/firewall
	
else
	echo -e "[ERROR]: Can not find firewall daemon"
	echo -e "This init system can not be supported"
	exit 1
fi

# check existence files:
if [ ! -e "$path2/start" ]; then
	echo -e "[ERROR]: $path2/start script\nNot exist"
	exit 1
elif [ ! -e "$path2/start_types" ]; then
	echo -e "[ERROR]: $path2/start_types script\nNot exist"
	exit 1
elif [ ! -e "$path2/stop" ]; then
	echo -e "[ERROR]: $path2/stop script\nNot exist"
	exit 1
elif [ ! -e "$path2/block" ]; then
	echo -e "[ERROR]: $path2/block script\nNot exist"
	exit 1
elif [ ! -e "$path2/iface.conf" ]; then
	echo -e "[ERROR]: $path3\nThis file not exist"
fi

bool=0 # is true

# permission of execution value
for n in {"$path1","$path2/start","$path2/start_types","$path2/stop","$path2/block"}                      
do
	if [ ! -x "$n" ]; then
		bool=1 # is false
		echo -e "\n [WARNING]: $n\n Permission denied."
		echo -e " Is not correctly set the execute permission:"
	fi		
done

if [ $bool = 1 ]; then
	exit 1
fi

# run daemon
$path1 $1

exit 0
