#!/bin/bash
#
# PROGRAM-NAME: parser_loader
# VERSION: (Ver.0.12) Tuesday, 14 August 2012
# DESCRIPTION: making parsing of interfaces set in iface.conf and proceed for 
#              load  with start, stop or block
# AUTHOR: Gianluca Pernigotto <jeanlucperni@gmail.com>
# 
# Copyright 2012  Gianluca Pernigotto, All rights reserved.
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if [ $(id -u) -ne 0 ]; then
        echo -e "\nPermission denied\n"
        exit 1
fi

ipt=`which iptables`
path2=/etc/pyfirewall/0.12

if [ "$1" = "start" ]; then

	sett=`sed 's/ *//g' $path2/iface.conf | grep '^interface' | sed -e '/^#/d' | sed -e 's/=.*$//g'`

	if [[ "$sett" == "interface_all" ]]; then
		inet=""
		/etc/pyfirewall/0.12/rules_single_interface.conf "${inet}"
		exit 0


	elif [[ "$sett" == "interface_match" ]]; then
		inet=`sed 's/ *//g' $path2/iface.conf | grep '^interface' | sed '/^$/d' | sed -e '/^#/d' | sed -e 's/interface_match=//g'`
		/etc/pyfirewall/0.12/rules_single_interface.conf "-i ${inet}"
		exit 0

	elif [[ "$sett" == "interface_list" ]]; then
		inet=`cat $path2/iface.conf | grep '^interface' | sed '/^$/d' | sed -e '/^#/d' | sed -e 's/interface_list=//g'`
		/etc/pyfirewall/0.12/rules_multi_interfaces.conf "${inet}"
		exit 0

	elif [[ "$sett" == "" ]]; then
		inet=""
		/etc/pyfirewall/0.12/rules_single_interface.conf "${inet}"
		exit 0


	else
		echo "[ERROR]: $path2/iface.conf (troppe righe decommentate?)"
		exit 1
	fi

	exit 0
fi

if [ "$1" = "stop" ]; then
	  
	############################
        # Reset delle impostazioni #
        ############################		
	$ipt -t nat -F
        $ipt -t nat -X
        $ipt -t nat -Z

        $ipt -t mangle -F
        $ipt -t mangle -X
        $ipt -t mangle -Z

        $ipt -F
        $ipt -X
        $ipt -Z
		
	################################
        # Impostazione Policy standard #
        ################################
	$ipt -P INPUT   ACCEPT
	$ipt -P FORWARD ACCEPT
	$ipt -P OUTPUT  ACCEPT
	exit 0
fi

if [ "$1" = "block" ]; then

	############################
	# Reset delle impostazioni #
	############################		
	$ipt -t nat -F
        $ipt -t nat -X
        $ipt -t nat -Z

        $ipt -t mangle -F
        $ipt -t mangle -X
        $ipt -t mangle -Z

        $ipt -F
        $ipt -X
        $ipt -Z
			
	################################
	# Impostazione Policy standard #
	################################
	$ipt -P INPUT   DROP
	$ipt -P FORWARD DROP
	$ipt -P OUTPUT  DROP
	exit 0
fi
